### PR TITLE
Standardise dev tooling

### PR DESCRIPTION
**Pull request by NorfairKing**

### CODE REVIEW

**Review by damianfral — CHANGES_REQUESTED** [review]
Launched a nix-shell, executed `stack build` and got this:
```
❯ stack build
<<<<<<<<<<<<<<<<<<
You are currently using Stack version 2.3.3, but version 2.5.1.1 is available
You can try to upgrade by running 'stack upgrade'
Tired of seeing this? Add 'recommend-stack-upgrade: false' to /home/damian/.stack/config.yaml
>>>>>>>>>>>>>>>>>>


UnliftIO.Exception.throwString called with:

In Nix shell but reExecL is False
Called from:
  throwString (src/Stack/Runners.hs:120:18 in stack-2.3.3-3g9P8h2rCn558ktT60sdpS:Stack.Runners)
```

I did a quick search and found this, https://github.com/commercialhaskell/stack/issues/5000#issuecomment-522442052, run `unset STACK_IN_NIX_SHELL` and then it worked; so, I'd like to know if you had experienced this and if we should remove this env var on the nix shell hook.

**Comment by damianfral** [comment]
@NorfairKing , I just saw this, https://github.com/commercialhaskell/stack/pull/5524 :smile:

**Comment by NorfairKing** [comment]
> Launched a nix-shell, executed `stack build` and got this:
> 
> ```
> ❯ stack build
> <<<<<<<<<<<<<<<<<<
> You are currently using Stack version 2.3.3, but version 2.5.1.1 is available
> You can try to upgrade by running 'stack upgrade'
> Tired of seeing this? Add 'recommend-stack-upgrade: false' to /home/damian/.stack/config.yaml
> >>>>>>>>>>>>>>>>>>
> 
> 
> UnliftIO.Exception.throwString called with:
> 
> In Nix shell but reExecL is False
> Called from:
>   throwString (src/Stack/Runners.hs:120:18 in stack-2.3.3-3g9P8h2rCn558ktT60sdpS:Stack.Runners)
> ```
> 
> I did a quick search and found this, [commercialhaskell/stack#5000 (comment)](https://github.com/commercialhaskell/stack/issues/5000#issuecomment-522442052), run `unset STACK_IN_NIX_SHELL` and then it worked; so, I'd like to know if you had experienced this and if we should remove this env var on the nix shell hook.

I figured you'd run into this :p
This is fixed as of two days ago: https://github.com/commercialhaskell/stack/pull/5524

In the meantime, you can run `stack test --file-watch` from outside of the nix shell and it will use the shell as part of the stack <-> nix integration.

**Review by damianfral — APPROVED** [review]
LGTM!

**Review by vidocco — APPROVED** [review]
LGTM

**Pull request merged**
